services:
  - type: web
    name: coursecompass-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PASSWORD
        sync: false
